#include "NumberDeviceClass.h"

const char* NumberDeviceClass::getName() const {
  static const char* names[] = {
      "none",
      "absolute_humidity",
      "apparent_power",
      "aqi",
      "area",
      "atmospheric_pressure",
      "battery",
      "blood_glucose_concentration",
      "carbon_dioxide",
      "carbon_monoxide",
      "current",
      "data_rate",
      "data_size",
      "distance",
      "duration",
      "energy",
      "energy_distance",
      "energy_storage",
      "frequency",
      "gas",
      "humidity",
      "illuminance",
      "irradiance",
      "moisture",
      "monetary",
      "nitrogen_dioxide",
      "nitrogen_monoxide",
      "nitrous_oxide",
      "ozone",
      "ph",
      "pm1",
      "pm25",
      "pm4",
      "pm10",
      "power_factor",
      "power",
      "precipitation",
      "precipitation_intensity",
      "pressure",
      "reactive_energy",
      "reactive_power",
      "signal_strength",
      "sound_pressure",
      "speed",
      "sulphur_dioxide",
      "temperature",
      "temperature_delta",
      "volatile_organic_compounds",
      "volatile_organic_compounds_parts",
      "voltage",
      "volume",
      "volume_flow_rate",
      "volume_storage",
      "water",
      "weight",
      "wind_direction",
      "wind_speed",
  };

  uint8_t index = static_cast<uint8_t>(deviceClass);
  if (index < sizeof(names) / sizeof(names[0])) {
    return names[index];
  }
  return "unknown";
}
